####################################################################################
#                        !!!    W  A  R  N  I  N  G    !!!                         #
# This file provides general configuration.                                        #
# Never delete this file. Otherwise, the package is broken and will stop working!  #
# Only edit if you know what you're doing.                                         #
# Exception: You can add additional filter sensors to the trigger from line 88     #
####################################################################################

rest_command:
  ambientika_authenticate:
    url: "https://app.ambientika.eu:4521/users/authenticate"
    method: POST
    headers:
      accept: "application/json"
    payload: '{"username":"{{ username }}","password":"{{ password }}"}'
    content_type: "application/json"

  ambientika_change_mode:
    url: "https://app.ambientika.eu:4521/device/change-mode"
    method: POST
    headers:
      accept: "application/json"
      Authorization: >
        Bearer {{ states("input_text.ambientika_access_token") }}
    payload: '{"deviceSerialNumber":"{{ serial }}","operatingMode":{{ mode }},"fanSpeed":{{ fan }},"humidityLevel":{{ humidity }},"lightSensorLevel":{{ light }}}'
    content_type: "application/json"

  ambientika_reset_filter:
    url: '{{ rest_url }}'
    method: GET
    headers:
      accept: "application/json"
      Authorization: >
        Bearer {{ states("input_text.ambientika_access_token") }}
    content_type: "application/json"


input_text:
  ambientika_access_token:
    name: Ambientika Access-Token
    mode: password
    max: 255
    initial: ""
    icon: mdi:key-chain

recorder:
  exclude:
    entities:
      - input_text.ambientika_access_token


automation:
  - id: automation.ambientika_authenticate
    alias: Ambientika Authenticate
    description: ""
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: numeric_state
        entity_id:
          - sensor.ambientika_token_remaining_days
        below: 5
    condition: []
    action:
      - service: rest_command.ambientika_authenticate
        metadata: {}
        data:
          username: !secret ambientika_username
          password: !secret ambientika_password
        response_variable: response
      - service: input_text.set_value
        metadata: {}
        data:
          value: "{{ response.content.jwtToken }}"
        target:
          entity_id: input_text.ambientika_access_token
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.ambientika_token_remaining_days


  - id: automation.ambientika_filter_notification
    alias: Ambientika Filter Notification and Reset 
    description: ""
    mode: single
    trigger:
      - platform: state
        entity_id:
          - sensor.ambientika_master_1_filter_status
          - sensor.ambientika_slave_2_filter_status
        to: Bad
        id: bad_filter
      - platform: event
        event_type: mobile_app_notification_action
        event_data:
          action: RESET_FILTER
        id: reset_filter
    condition: []
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - bad_filter
            sequence:
              - variables:
                  area: "{{ area_name(trigger.entity_id) }}"
                  short_name: >-
                    Ambientika {{ state_attr(trigger.entity_id,
                    'friendly_name').split(' ')[1] }}
                  message: >-
                    The filter of your <b>{{short_name}}</b> is in bad condition.
                    <b>Please clean</b> it and reset the working hours.
              - action: notify.notify
                data:
                  title: Ambiantika Filter
                  message: "{{ message}}"
                  data:
                    tag: "{{ trigger.entity_id }}"
                    visibility: public
                    sticky: "true"
                    notification_icon: mdi:air-filter
                    actions:
                      - action: RESET_FILTER
                        title: Reset Filter
          - conditions:
              - condition: trigger
                id:
                  - reset_filter
            sequence:
              - variables:
                  device_serial: "{{ state_attr(trigger.event.data.tag, 'device_serial') }}"
              - action: rest_command.ambientika_reset_filter
                metadata: {}
                data:
                  rest_url: >-
                    {{ 'https://app.ambientika.eu:4521/device/reset-filter' ~
                    '?deviceSerialNumber=' ~ device_serial }}
                response_variable: result
              - if:
                  - condition: template
                    value_template: "{{ result.status == 200 }}"
                then:
                  - action: notify.notify
                    metadata: {}
                    data:
                      message: clear_notification
                      data:
                        tag: "{{ trigger.event.data.tag }}"
                else:
                  - action: notify.notify
                    metadata: {}
                    data:
                      title: ⚠️ Ambientika Filter-Reset failed
                      message: >-
                        Automatic filter reset failed. Please use the official app
                        to reset the filter status.


homeassistant:
  customize:
    automation.ambientika_authenticate:
      icon: mdi:key-chain
    automation.ambientika_filter_notification_and_reset:
      icon: mdi:air-filter


sensor:
  - platform: rest
    unique_id: ambientika_token_duration
    name: Ambientika Token, remaining Days
    resource: "https://app.ambientika.eu:4521/users/token-info"
    headers:
      Authorization: >
        Bearer {{ states("input_text.ambientika_access_token") }}
    value_template: >
      {% if value_json.validTo | is_defined %}
        {% set remaining_days = ( value_json.validTo|as_timestamp - now()|as_timestamp )/60/60/24 %}
        {{ remaining_days | round(0) | default(0) }}
      {% else %} undefined {% endif %}
    icon: mdi:key-chain
    scan_interval: 3600
