automation:
  - id: automation.ambientika_authenticate
    alias: Ambientika Authenticate
    description: ""
    mode: single
    trigger:
      - platform: homeassistant
        event: start
      - platform: numeric_state
        entity_id:
          - sensor.ambientika_token_remaining_days
        below: 5
    condition: []
    action:
      - service: rest_command.ambientika_authenticate
        metadata: {}
        data:
          username: !secret ambientika_username
          password: !secret ambientika_password
        response_variable: response
      - service: input_text.set_value
        metadata: {}
        data:
          value: "{{ response.content.jwtToken }}"
        target:
          entity_id: input_text.ambientika_access_token
      - service: homeassistant.update_entity
        target:
          entity_id: sensor.ambientika_token_remaining_days

  - id: automation.ambientika_1_change_mode
    alias: Ambientika 1 Change-Mode
    description: ""
    mode: single
    trigger:
      - platform: state
        entity_id:
          - input_select.ambientika_1_mode
          - input_number.ambientika_1_fanspeed
          - input_number.ambientika_1_humiditylevel
        id: change_mode
      - platform: state
        entity_id:
          - sensor.ambientika_1_operating_mode
          - sensor.ambientika_1_fan_speed
          - sensor.ambientika_1_humidity_level
        id: mode_changed
    condition:
      - condition: template
        value_template: >-
          {{ now() > as_datetime(this.attributes.last_triggered, today_at("00:00")) + timedelta(seconds=2) }}
    action:
      - choose:
          - conditions:
              - condition: trigger
                id:
                  - change_mode
            sequence:
              - service: rest_command.ambientika_change_mode
                data:
                  serial: !secret serial_device-1
                  mode: '"{{ states("input_select.ambientika_1_mode") }}"'
                  fan: "{{ states('input_number.ambientika_1_fanSpeed')|int - 1 }}"
                  humidity: "{{ states('input_number.ambientika_1_humidityLevel')|int - 1 }}"
              - delay:
                  hours: 0
                  minutes: 0
                  seconds: 3
                  milliseconds: 0
              - service: homeassistant.update_entity
                data: {}
                target:
                  entity_id: sensor.ambientika_1_operating_mode
          - conditions:
              - condition: trigger
                id:
                  - mode_changed
              - condition: template
                value_template:
                  "{{ states('sensor.ambientika_1_operating_mode') not in ['unavailable', 'unknown'] and
                  states('sensor.ambientika_1_fan_speed') not in ['unavailable', 'unknown'] and
                  states('sensor.ambientika_1_humidity_level') not in ['unavailable', 'unknown'] }}"
            sequence:
              - action: input_select.select_option
                target:
                  entity_id: input_select.ambientika_1_mode
                data:
                  option: "{{ states('sensor.ambientika_1_operating_mode') }}"
              - variables:
                  fanspeed:
                    "{% if states('sensor.ambientika_1_fan_speed') == 'Low' %} 1
                    {% elif states('sensor.ambientika_1_fan_speed') == 'Medium' %} 2
                    {% elif states('sensor.ambientika_1_fan_speed') == 'High' %} 3
                    {% else %} {{ states('input_number.ambientika_1_fanspeed') }}
                    {% endif %}"
                  humiditylevel:
                    "{% if states('sensor.ambientika_1_humidity_level') == 'Dry' %} 1
                    {% elif states('sensor.ambientika_1_humidity_level') == 'Normal' %} 2
                    {% elif states('sensor.ambientika_1_humidity_level') == 'Moist' %} 3
                    {% else %} {{ states('input_number.ambientika_1_humiditylevel') }}
                    {% endif %}"
              - action: input_number.set_value
                target:
                  entity_id: input_number.ambientika_1_fanspeed
                data:
                  value: "{{ fanspeed|float }}"
              - action: input_number.set_value
                target:
                  entity_id: input_number.ambientika_1_humiditylevel
                data:
                  value: "{{ humiditylevel|float }}"
