# here, MULTIPLE sensors are set up using the same REST-endpoint
rest:
  - resource: !secret device-status-1
    headers:
      Authorization: >
        Bearer {{ states("input_text.ambientika_access_token") }}
    sensor:
      - unique_id: ambientika_1_operatingMode
        value_template: "{{ value_json.operatingMode | is_defined }}"
        name: Ambientika 1 Operating Mode
        icon: mdi:leaf-circle-outline
      - unique_id: ambientika_1_lastOperatingMode
        value_template: "{{ value_json.lastOperatingMode | is_defined }}"
        name: Ambientika 1 lastOperatingMode
      - unique_id: ambientika_1_fanSpeed
        value_template: "{{ value_json.fanSpeed | is_defined }}"
        # this is the defined fan speed for Mode: "ManualHeatRecovery"
        name: Ambientika 1 Fan-Speed
        icon: >-
          {% if states('sensor.ambientika_1_fan_speed') == 'Low' %}
          mdi:fan-speed-1
          {% elif states('sensor.ambientika_1_fan_speed') == 'Medium' %}
          mdi:fan-speed-2
          {% elif states('sensor.ambientika_1_fan_speed') == 'High' %}
          mdi:fan-speed-3
          {% else %} mdi:fan-alert {% endif %}
      - unique_id: ambientika_1_humidityLevel
        value_template: "{{ value_json.humidityLevel | is_defined }}"
        # this is the defined humidityLevel for Mode: "Auto" and "Survillance"
        name: Ambientika 1 Humidity-Level
        icon: mdi:water
      - unique_id: ambientika_1_filtersStatus
        value_template: "{{ value_json.filtersStatus | is_defined }}"
        name: Ambientika 1 Filter-Status
        icon: mdi:air-filter
      - unique_id: ambientika_1_temperature
        value_template: "{{ float(value_json.temperature, default='unavailable') }}"
        name: Ambientika 1 Temperature (raw)
        icon: mdi:thermometer
        device_class: temperature
        unit_of_measurement: "°C"
      - unique_id: ambientika_1_humidity
        value_template: "{{ float(value_json.humidity, default='unavailable') }}"
        name: Ambientika 1 Humidity (raw)
        icon: mdi:water-percent
        device_class: humidity
        unit_of_measurement: "%"
      - unique_id: ambientika_1_airQuality
        value_template: "{{ value_json.airQuality | is_defined }}"
        name: Ambientika 1 Air-Quality
        icon: mdi:molecule-co2
    binary_sensor:
      - unique_id: ambientika_1_humidityAlarm
        value_template: "{{ value_json.humidityAlarm | is_defined }}"
        name: Ambientika 1 Humidity-Alarm
        icon: mdi:water-percent-alert
      - unique_id: ambientika_1_nightAlarm
        value_template: "{{ value_json.nightAlarm | is_defined }}"
        name: Ambientika 1 Night-Alarm
        icon: mdi:water-percent-alert


# here, a SINGLE sensors is set up using a specific REST-endpoint
sensor:
  - platform: rest
    unique_id: ambientika_token_duration
    name: Ambientika Token, remaining Days
    resource: "https://app.ambientika.eu:4521/users/token-info"
    headers:
      Authorization: >
        Bearer {{ states("input_text.ambientika_access_token") }}
    value_template: >
      {% if value_json.validTo | is_defined %}
        {% set remaining_days = ( value_json.validTo|as_timestamp - now()|as_timestamp )/60/60/24 %}
        {{ remaining_days | round(0) | default(0) }}
      {% else %} undefined {% endif %}
    icon: mdi:key-chain
    scan_interval: 3600

# since the raw values from the device sensors have plenty of jitter,
# the values are filtered, using settings documented in readme.md
  - platform: filter
    unique_id: ambientika_1_humidity_filtered
    name: Ambientika 1 Humidity (filtered)
    entity_id: sensor.ambientika_1_humidity_raw
    filters:
      - filter: time_simple_moving_average
        window_size: "00:09"
        precision: 0
      - filter: lowpass
        time_constant: 3
        precision: 0
  
  - platform: filter
    unique_id: ambientika_1_temperature_filtered
    name: Ambientika 1 Temperature (filtered)
    entity_id: sensor.ambientika_1_temperature_raw
    filters:
      - filter: time_simple_moving_average
        window_size: "00:05"
        precision: 1
